Remove dialyzer from CI

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -8,7 +8,10 @@
 MIX_ENV=test mix format --check-formatted || { echo 'Please format code using `mix format`.'; exit 1; }
 MIX_ENV=test mix compile --warnings-as-errors --force || { echo 'Please fix all compiler warnings.'; exit 1; }
 MIX_ENV=test mix docs || { echo 'Elixir HTML docs were not generated!'; exit 1; }
-MIX_ENV=test mix dialyze || { echo 'Dialyzer checks failed.'; exit 1; }
+
+if [ ! $CI ]; then
+  MIX_ENV=test mix dialyze || { echo 'Dialyzer checks failed.'; exit 1; }
+fi
 
 if [ $CI ]; then
   mix coveralls.travis || { echo 'Elixir tests failed!'; exit 1; }
